# Generated by Django 4.1.3 on 2022-11-09 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 9, 14, 19, 51, 604070)
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("organisation", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
